package com.lhind.shorturi.service;

import com.lhind.shorturi.entity.Role;
import com.lhind.shorturi.entity.UrlMapping;
import com.lhind.shorturi.entity.User;
import com.lhind.shorturi.entity.dto.request.UrlRequestDto;
import com.lhind.shorturi.entity.dto.response.ShortUrlAdminInfoResponseDto;
import com.lhind.shorturi.repository.UrlMappingRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class UrlMappingServiceTest {

    @Mock
    private UrlMappingRepository urlMappingRepository;

    @Mock
    private UserService userService;

    @InjectMocks
    private UrlMappingService urlMappingService;

    @Test
    void testSaveOriginalUrl_shortUrlExist_returnUniqueShortUrl() throws Exception {
//        Given
        String username = "lisen@test.al";
        int expirationMinutes = 10;
        UrlRequestDto dto = new UrlRequestDto("https://example.com?param=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvvvvvvvvvvvv");
        UrlMapping existing = new UrlMapping();
        existing.setLongUrl(dto.url());

//        When
        when(urlMappingRepository.findByLongUrlAndExpirationTimeAfter(eq(dto.url()), any())).thenReturn(Optional.of(existing));
        when(urlMappingRepository.save(any())).thenAnswer(invocation -> invocation.getArgument(0));

//        Then
        UrlMapping result = urlMappingService.saveOriginalUrlAndReturnUniqueShortUrl(dto, expirationMinutes, username);

        assertEquals(dto.url(), result.getLongUrl());
        assertEquals(LocalDateTime.now().plusMinutes(10).truncatedTo(ChronoUnit.SECONDS), result.getExpirationTime().truncatedTo(ChronoUnit.SECONDS));
        assertEquals(username, result.getUpdatedBy());
        assertNotNull(result.getExpirationTime());
    }

    @Test
    void testSaveOriginalUrl_shortUrlNotExist_andReturnUniqueShortUrl() throws Exception {
//        Given
        String username = "lisen@test.al";
        int expirationMinutes = 5;
        UrlRequestDto dto = new UrlRequestDto("https://example.com?param=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvvvvvvvvvvvv");
        LocalDateTime now = LocalDateTime.now();
        var shortenUrlAutoGenerated = "bTywlmGPNE";
//        When
        when(urlMappingRepository.findByLongUrlAndExpirationTimeAfter(eq(dto.url()), any())).thenReturn(Optional.empty());
        when(urlMappingRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

//        Then
        UrlMapping result = urlMappingService.saveOriginalUrlAndReturnUniqueShortUrl(dto, expirationMinutes, username);

        assertEquals(dto.url(), result.getLongUrl());
        assertEquals(result.getShortUrl(), shortenUrlAutoGenerated);
        assertNotNull(result.getShortUrl());
    }

    @Test
    void testGetShortUrlUniqueGenerated() {
//        Given
        String url = "https://example.com?param=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvvvvvvvvvvvv";

//        When
        when(urlMappingRepository.findByShortUrl(any())).thenReturn(Optional.empty());

//        Then
        String result = urlMappingService.getShortUrlUniqueGenerated(url);

        assertNotNull(result);
        assertTrue(result.length() <= 10);
    }

    @Test
    void testFindByShortUrl() {
//        Given
        UrlMapping urlMapping = new UrlMapping();
        urlMapping.setShortUrl("exmp_123");
        urlMapping.setLongUrl("https://example.com?param=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvvvvvvvvvvvv");

//        When
        when(urlMappingRepository.findByShortUrl("exmp_123")).thenReturn(Optional.of(urlMapping));

//        Then
        Optional<UrlMapping> result = urlMappingService.findByShortUrl("exmp_123");

        assertTrue(result.isPresent());
        assertEquals("exmp_123", result.get().getShortUrl());
        assertEquals("https://example.com?param=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbvvvvvvvvvvvvvvvvvvvvvvvvvvv", result.get().getLongUrl());
    }

    @Test
    void findByLongUrl() {
    }

    @Test
    void testIncrementClickCount() {
//        Given
        UrlMapping urlMapping = new UrlMapping();
        urlMapping.setClickCount(3);

//        When
        when(urlMappingRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

        urlMappingService.incrementClickCount(urlMapping);

//        Then
        assertEquals(4, urlMapping.getClickCount());
    }


    @Test
    void testGetAllShortenUrl_caseRoleAdmin() {
//        Given
        User user = new User();
        user.setRole(Role.ADMIN);

//        When
        when(userService.findByUsername("admin@test.al")).thenReturn(user);
        when(urlMappingRepository.findAll()).thenReturn(List.of(new UrlMapping()));

//        Then
        List<?> result = urlMappingService.getAllShortenUrl("admin@test.al");

        assertFalse(result.isEmpty());
        assertTrue(result.get(0) instanceof ShortUrlAdminInfoResponseDto);
    }

    @Test
    void testGetAllShortenUrl_caseRoleUser() {
//        Given
        User user = new User();
        user.setRole(Role.USER);

//        When
        when(userService.findByUsername("lisen@test.al")).thenReturn(user);
        when(urlMappingRepository.findAll()).thenReturn(List.of(new UrlMapping()));

//        Then
        List<?> result = urlMappingService.getAllShortenUrl("lisen@test.al");

        assertFalse(result.isEmpty());
        assertFalse(result.get(0) instanceof ShortUrlAdminInfoResponseDto);
    }

    @Test
    void testDeleteUrlMapping() {
//        Given
        UrlMapping urlMapping = new UrlMapping();

//        When
        doNothing().when(urlMappingRepository).delete(urlMapping);

//        Then
        assertDoesNotThrow(() -> urlMappingService.deleteUrlMapping(urlMapping));
    }

}