version: '3'

services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: p@5Sw0Rd
      POSTGRES_USER: user
      POSTGRES_DB: shorturidb
    ports:
      - '5432:5432'
    volumes:
      - shorturi-pg-db:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
      - '85:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: lisen@student.edu
      PGADMIN_DEFAULT_PASSWORD: lisen123

volumes:
  shorturi-pg-db:
